---
  - name: config ELK VM with Docker
    hosts: elk
    become: true
    tasks:
      - name: Install packages
        sysctl:
          name: vm.max_map_count
          value: "262144"
          sysctl_set: yes
          reload: yes
      - name: docker.io
        apt:
          update_cache: yes
          name: docker.io
          state: present
      - name: install pip3
        apt:
          force_apt_get: yes
          name: python3-pip
          state: present
      - name: install python docker module
        pip:
          name: docker
          state: present
      - name: download docker container
        docker_container:
          name: elk
          image: sebp/elk:761
          state: started
          restart_policy: always
          published_ports:
            - 5601:5601
            - 9200:9200
            - 5044:5044

      - name: Enable docker service
        systemd:
          name: docker
          enabled: yes


